### ISSUE TITLE
B-C panel

### ISSUE THREAD

**Issue by vanjakle** [Klepac-Ceraj-Lab/Resonance#103]
To me, it's more intuitive to have panels B and C flipped. you first generate panel C in order to get the B.

**Comment by kescobo** [comment]
Which figure is this for?

**Comment by vanjakle** [comment]
Figure 1:
panel A:
top graph - make x-legend to be Age (months) and remove m next to numbers
Lower schematic - fix fonts. text is unreadable. Something happened to the figure's resolution. 

Panel B and C - flip as you first generate panel C in order to get the coordinate for panel B.

**Comment by kescobo** [comment]
>Panel B and C - flip as you first generate panel C in order to get the coordinate for panel B.

I don't understand this point - I do MDS to get both the X axis for B and both axes for C.

**Comment by vanjakle** [comment]
That's fine if you want to keep it as is. To me, it makes more sense to show C first, then B.
