### ISSUE TITLE
Unify how we talk about importances

### ISSUE THREAD

**Issue by kescobo** [Klepac-Ceraj-Lab/Resonance#114]
Right now we use different ideas - Eg relative % or rank or raw numbers. We should change everything to relative % and put it in context

**Comment by kescobo** [comment]
@Hugemiler I think we've done this, yes?

**Comment by kescobo** [comment]
Answer from https://github.com/Klepac-Ceraj-Lab/guilhermefahurbottino/pull/25 is no - let's do this.

**Comment by Hugemiler** [comment]
ON the analysis side, closed by #135 on the text side, closed by #144
