### ISSUE TITLE
Code review from #125

### ISSUE THREAD

**Issue by kescobo** [Klepac-Ceraj-Lab/Resonance#126]
See #125.

**Comment by Hugemiler** [comment]
Done on #135

**Comment by kescobo** [comment]
Let's not close until that PR is actually merged. You can actually type `closes #126` in that PR, and then this one will automatically close when that PR gets merged.

**Comment by kescobo** [comment]
I just set it up: 

![image](https://user-images.githubusercontent.com/3502975/227330370-6d63d2cd-95b5-40c5-98ab-62f36ec0686f.png)
