### ISSUE TITLE
:exclamation: Do this last :exclamation: 

### ISSUE THREAD

**Issue by kescobo** [Klepac-Ceraj-Lab/Resonance#130]
Just before submission, the following steps need to be taken / confirmed:

- [x]  @kescobo Put latest versions of figures [into gdrive](https://drive.google.com/drive/folders/1vXGHjTYA5rAfouVWg8MzUnbr7ha_Lx6u)
- [x] @kescobo Put latest versions of supplementary figures [into gdrive](https://drive.google.com/drive/folders/1vXGHjTYA5rAfouVWg8MzUnbr7ha_Lx6u)
- [x] @kescobo Put latest versions of supplementary tables [into gdrive](https://drive.google.com/drive/folders/1vXGHjTYA5rAfouVWg8MzUnbr7ha_Lx6u)
- [x] @kescobo create github release, add zenodo citation to LaTeX document.
- [x] @kescobo compile LaTeX manuscript and add [into gdrive](https://drive.google.com/drive/folders/1vXGHjTYA5rAfouVWg8MzUnbr7ha_Lx6u)
    - [ ] ~~Include bibliography inside `.tex` file. See https://www.science.org/content/page/preparing-manuscripts-using-latex~~ Apparently not for initial submission (see comment below)
- [x] @kescobo Generate [supplementary materials](https://www.science.org/content/page/science-advances-information-authors#supplementary-materials) PDF 
- [x] @vanjakle  Do one final read-through
- [x] @Hugemiler  Do one final read-through
- [x] @kescobo Do one final read-through
- [ ] @kescobo update bioRxiv preprint
- [ ] @vanjakle Submit! https://cts.sciencemag.org/scc/#/login

**Comment by kescobo** [comment]
>Initial submission: To prepare your manuscript in LaTeX, please follow the LaTeX source guidelines below. Generate PDF files for the main text and Supplementary Materials, and upload them in the “Manuscript” and “Supplementary Materials” sections of the “Article” and “Related Documents” tabs. The figures should be included in the PDF files; do not upload them separately at this stage (see the section on Figures in the LaTeX source guidelines below).

**Comment by kescobo** [comment]
## Other ToDos

- [ ] Change title

**Comment by vanjakle** [comment]
continuing with the previous... 

- [ ] Lns 137 and 166 - checked the wording with Libusha. She says to use "correlate" instead.
- [ ] Ln 328 - add spaces as elsewhere in text you have a space around "="
- [ ] Ln 349 - Functional should not be capitalized
- [ ] Ln 352 - looks odd to have one sentence paragraph. combine it with the next paragraph. 
- [ ] Ln 354 - remove "Machine Learning Framework"?
- [ ] Ln 377 - I think there's an extra space btw. "under" and "4".
- [ ] Ln 378 - add space btw. "methods" and "(71)".
- [ ] Ln 384 - add space btw. "approach" and "(72)".
- [ ] Ln 387 - change "volune" to "volume".
- [ ] Ln 388 - add space btw each and (74).
- [ ] Ln 389 - one sentence paragraph. Can you combine it with the previous paragraph or add another sentence?
- [ ] Ln 392 - use a different word from "paper". maybe "study"? and "manuscript"?
- [ ] Ln 397 - change github to GitHub.
- [ ] Ln 398/399 - remove one "References"

**Comment by vanjakle** [comment]
ToDos - Supplementary Material

- [ ] Change title to reflect the manuscript title. 
- [ ] Table titles go above tables. (applies to all tables)

**Comment by vanjakle** [comment]
- [ ] Please review the Letter to Editor (https://docs.google.com/document/d/1ZnOYFZlWt0PpSWiIhPeUoHQdpxafQ_bmy0x8UrKw0c0/edit)

**Comment by Hugemiler** [comment]
Line 367, "...refer to _proportions of_ the average..."

**Comment by Hugemiler** [comment]
Line 153 and legend to Figure 3: "80%" => "60%".

**Comment by kescobo** [comment]
> Lns 137 and 166. "predict" in the title. I understand that the model predicts the outcome based on the inputs. however, to a non-ML person, the word predict means something else and that is predicting the future outcome. Would "correlate" be more appropriate here?

I don't think "correlate" captures the right meaning. "Predict" is not only an ML thing, but I kinda agree. @Hugemiler Can you think of a different word that might work? Also, removing the "functional profiles" from that line, since we don't use them.

**Comment by kescobo** [comment]
> Section after Ln 166 - unclear if all samples with MRIs were used to predict brain structure differences or if you grouped by age. Add a sentence somewhere that all participants, regardless of age, were included in the model. Also, unclear how many samples/participants were included. or if they were the same as the ones that were used to predict cog scores.

@Hugemiler This was all subjects, right?

**Comment by Hugemiler** [comment]
> > Section after Ln 166 - unclear if all samples with MRIs were used to predict brain structure differences or if you grouped by age. Add a sentence somewhere that all participants, regardless of age, were included in the model. Also, unclear how many samples/participants were included. or if they were the same as the ones that were used to predict cog scores.
> 
> @Hugemiler This was all subjects, right?

This was subjects 18 to 120 months, 1 row per subject, first stool sample inside this age bracket with a matching MRI scan. Total 121 datapoints.

**Comment by Hugemiler** [comment]
> > Lns 137 and 166. "predict" in the title. I understand that the model predicts the outcome based on the inputs. however, to a non-ML person, the word predict means something else and that is predicting the future outcome. Would "correlate" be more appropriate here?
> 
> I don't think "correlate" captures the right meaning. "Predict" is not only an ML thing, but I kinda agree. @Hugemiler Can you think of a different word that might work? Also, removing the "functional profiles" from that line, since we don't use them.
> 
> > Vanja: Lns 137 and 166 - checked the wording with Libusha. She says to use "correlate" instead.

I'm extremely partial to "predict" over "correlate". I cannot think of a better word, and I do not think one exists. I understand that more and more papers are getting this audience used to this terminology (just google "metagenomics predict IBD" for example and see the high amount of recent papers where classifiers of same-time IBD/control were called "predictors").

I understand that historical data that predicts future data is often called "forecast" or "future prediction", where not implicit on a domain-specific context. If it's extremely important to emphasize that this is not a forecast, how do you feel about addin the word "concurrent" after "predict" ?

**Comment by Hugemiler** [comment]
@kescobo re removing "functional profiles", are ECs not a type of funcional profile? If we have test-set statistics for them on Table 2, should we not leave them?

**Comment by kescobo** [comment]
Hmm - I didn't catch that. I think it's weird that we don't say anything about it, nor do anything with those models.

**Comment by kescobo** [comment]
reverted acbfca8

**Comment by vanjakle** [comment]
- [ ] Acknowledgments - we forgot to thank Libusha and Daphne and also Sophie and Alexi (they were on the first version of the bioRxiv paper so we should include them at least in the acknowledgments! 
 - @kescobo could you please add something like this:
We thank Libusha Kelly (Albert Einstein School of Medicine) and Daphne Koinis Mitchell (Brown University) for helpful feedback on the manuscript. The research team also thanks the participants and families of the participants who generously shared their time and samples for this project.

**Comment by vanjakle** [comment]
- [ ] @kescobo - could I please get a combined pdf? 

> Upload a combined pdf that includes the complete main manuscript, figures, and supplementary materials. The combined pdf is used for the evaluation process and it is provided to reviewers.
